{
 "title": "Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:IN"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  {
   "type": "knightss27-weathermap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"spine1\", interface_name=\"ethernet-1/11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"spine1\", interface_name=\"ethernet-1/11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"spine1\", interface_name=\"ethernet-1/12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"spine1\", interface_name=\"ethernet-1/12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"spine1\", interface_name=\"ethernet-1/13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"spine1\", interface_name=\"ethernet-1/13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"spine2\", interface_name=\"ethernet-1/11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"spine2\", interface_name=\"ethernet-1/11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"spine2\", interface_name=\"ethernet-1/12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"spine2\", interface_name=\"ethernet-1/12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"spine2\", interface_name=\"ethernet-1/13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"spine2\", interface_name=\"ethernet-1/13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"leaf1\", interface_name=\"ethernet-1/21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"leaf1\", interface_name=\"ethernet-1/21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"leaf2\", interface_name=\"ethernet-1/21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"leaf2\", interface_name=\"ethernet-1/21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"leaf3\", interface_name=\"ethernet-1/21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"leaf3\", interface_name=\"ethernet-1/21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_total_received_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_disabled_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_srl_cpu_instant{source=\"$NE\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_mem_free{source=\"$NE\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "gnmic_srl_mem_utilization{source=\"$NE\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "gnmic_srl_mem_reserved{source=\"$NE\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "gnmic_srl_mem_physical{source=\"$NE\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Service: $Services",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gnmic_srl_net_instance_oper_state{network_instance_name='$Services'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "gnmic_srl_apps_pid{source='$NE'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  }
 ]
}